# DS 3000 - Assignment [TODO: enter assignment number]

**Student Name**: [TODO: Enter your name here]

**Date**: [TODO: Enter the date]


### Submission Instructions
Submit this `ipynb` file to canvas.

The `ipynb` format stores outputs from the last time you ran the notebook.  (When you open a notebook it has the figures and outputs of the last time you ran it too).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh run `Kernel > Restart & Run All` just before uploading the `ipynb` file to Canvas.

### Academic Integrity

**Writing your homework is an individual effort.**  You may discuss general python problems with other students but under no circumstances should you observe another student's code which was written for this assignment, from this year or past years.  Pop into office hours or DM us in MS Teams if you have a specific question about your work or if you would like another pair of eyes or talk through your code.

Don't forget to cite websites which helped you solve a problem in a unique way.  You can do this in markdown near the code or with a simple one-line comment. You do not need to cite the official python documentation.

**Documentation / style counts for credit**  Please refer to the Pep-8 style, to improve the readability and consistency of your Python code. For more information, read the following article [How to Write Beautiful Python Code With PEP 8](https://realpython.com/python-pep8/) or ask your TA's for tips.

**NOTE:<span style='color:red'> Write python expressions to answer ALL questions below and ensure that you use the `print()` function to display the output.</span>** Each question should be answered in a new code cell. For example, your solution for question 1.1 should be in a different code cell from your solution for question 1.2.

## PART 1: DATA PREPERATION
### Loading the dataset

In [1]:
# Import necessary libraries
import pandas as pd

# Load the dataset
heart_disease_df = pd.read_csv("heart_disease.csv")

# Display the first 50 rows of the dataframe
heart_disease_df.head(10)

,Gender,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,Heart_ stroke
0,Male,39,postgraduate,0,0.0,0.0,no,0,0,195.0,106.0,70.0,26.97,80.0,77.0,No
1,Female,46,primaryschool,0,0.0,0.0,no,0,0,250.0,121.0,81.0,28.73,95.0,76.0,No
2,Male,48,uneducated,1,20.0,0.0,no,0,0,245.0,127.5,80.0,25.34,75.0,70.0,No
3,Female,61,graduate,1,30.0,0.0,no,1,0,225.0,150.0,95.0,28.58,65.0,103.0,yes
4,Female,46,graduate,1,23.0,0.0,no,0,0,285.0,130.0,84.0,23.10,85.0,85.0,No
5,Female,43,primaryschool,0,0.0,0.0,no,1,0,228.0,180.0,110.0,30.30,77.0,99.0,No
6,Female,63,uneducated,0,0.0,0.0,no,0,0,205.0,138.0,71.0,33.11,60.0,85.0,yes
7,Female,45,primaryschool,1,20.0,0.0,no,0,0,313.0,100.0,71.0,21.68,79.0,78.0,No
8,Male,52,uneducated,0,0.0,0.0,no,1,0,260.0,141.5,89.0,26.36,76.0,79.0,No
9,Male,43,uneducated,1,30.0,0.0,no,1,0,225.0,162.0,107.0,23.61,93.0,88.0,No

## Inspecting the data to:
- Display information about the variables
- Display the data types of each column
- Display the unique values in each column

In [2]:
# Check the dimensions of the dataframe
dimensions = heart_disease_df.shape
print("Dimensions of the dataframe:", dimensions)

# Display information about the variables, including data types
data_info = heart_disease_df.info()

# Display the unique values in each column
unique_values = heart_disease_df.nunique()

# Display the data types of each column
data_types = heart_disease_df.dtypes

# Print the results
print("\nInformation about the variables:")
print(data_info)

print("\nUnique values in each column:")
print(unique_values)

print("\nData types of each column:")
print(data_types)

Dimensions of the dataframe: (4238, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4238 non-null   object
 1   age              4238 non-null   int64
 2   education        4133 non-null   object
 3   currentSmoker    4238 non-null   int64
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   object
 7   prevalentHyp     4238 non-null   int64
 8   diabetes         4238 non-null   int64
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  Heart_ stroke    4238 non-null   object
dtypes: float64(8), int64(4), object(4)
memory usage: 529.9+ KB

Information about the variables:
None

Unique values in each column:
Gender                2
age                  39
education             4
currentSmoker         2
cigsPerDay           33
BPMeds                2
prevalentStroke       2
prevalentHyp          2
diabetes              2
totChol             248
sysBP               234
diaBP               146
BMI                1363
heartRate            73
glucose             143
Heart_ stroke         2
dtype: int64

Data types of each column:
Gender              object
age                  int64
education           object
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke     object
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate          float64
glucose            float64
Heart_ stroke       object
dtype: object

## Types of Data
### Identifying two categorical variables and indicating if they are nominal or ordinal

In [3]:
# Check for 'Gender'
gender_column = 'Gender'
if gender_column in heart_disease_df.columns:
    unique_values = heart_disease_df[gender_column].unique()
    variable_type = 'Nominal'
    print(f"{gender_column}: {variable_type}")

# Check for 'education'
education_column = 'education'
if education_column in heart_disease_df.columns:
    unique_values = heart_disease_df[education_column].unique()
    variable_type = 'Ordinal'
    print(f"{education_column}: {variable_type}")

Gender: Nominal
education: Ordinal

### Finding the missing values

In [4]:
import pandas as pd

# Assuming 'heart_disease_df' is your dataframe
missing_values = heart_disease_df.isnull().sum()

missing_percentage = (missing_values / len(heart_disease_df)) * 100

missing_percentage = missing_percentage.round(2)

missing_info = pd.DataFrame({
    'Missing Values': missing_values,
    'Percentage': missing_percentage
})

print("Missing values information:")
print(missing_info)

Missing values information:
                 Missing Values  Percentage
Gender                        0        0.00
age                           0        0.00
education                   105        2.48
currentSmoker                 0        0.00
cigsPerDay                   29        0.68
BPMeds                       53        1.25
prevalentStroke               0        0.00
prevalentHyp                  0        0.00
diabetes                      0        0.00
totChol                      50        1.18
sysBP                         0        0.00
diaBP                         0        0.00
BMI                          19        0.45
heartRate                     1        0.02
glucose                     388        9.16
Heart_ stroke                 0        0.00

### Updating the Rows with the Missing Values

In [5]:
import pandas as pd

# Assuming 'heart_disease_df' is your dataframe
columns_with_missing_data = ['education', 'cigsPerDay', 'BPMeds', 'totChol', 'BMI', 'heartRate', 'glucose']

# Drop rows with missing values in the specified columns
heart_disease_df.dropna(subset=columns_with_missing_data, inplace=True)

# Display the updated dimensions of the DataFrame
updated_dimensions = heart_disease_df.shape
print(f"Updated Dimensions of the DataFrame: {updated_dimensions}")

# Check for missing values after the update
updated_missing_values = heart_disease_df.isnull().sum()
updated_missing_percentage = (updated_missing_values / len(heart_disease_df)) * 100

# Create a DataFrame with updated missing values information
updated_missing_info = pd.DataFrame({
    'Updated Missing Values': updated_missing_values,
    'Updated Percentage': updated_missing_percentage
})

# Print the updated missing values information
print("Updated Missing values information:")
print(updated_missing_info)

Updated Dimensions of the DataFrame: (3656, 16)
Updated Missing values information:
                 Updated Missing Values  Updated Percentage
Gender                                0                 0.0
age                                   0                 0.0
education                             0                 0.0
currentSmoker                         0                 0.0
cigsPerDay                            0                 0.0
BPMeds                                0                 0.0
prevalentStroke                       0                 0.0
prevalentHyp                          0                 0.0
diabetes                              0                 0.0
totChol                               0                 0.0
sysBP                                 0                 0.0
diaBP                                 0                 0.0
BMI                                   0                 0.0
heartRate                             0                 0.0
glucose                               0                 0.0
Heart_ stroke                         0                 0.0

## converting categorical variables into numerical format

In [6]:
from sklearn.preprocessing import LabelEncoder

# Assuming 'heart_disease_df' is your dataframe
label_encoder = LabelEncoder()

# Convert 'Gender' column to integers
heart_disease_df['Gender'] = label_encoder.fit_transform(heart_disease_df['Gender'])

# Convert 'education' column to integers
heart_disease_df['education'] = label_encoder.fit_transform(heart_disease_df['education'])

# Convert 'prevalentStroke' column to integers
heart_disease_df['prevalentStroke'] = label_encoder.fit_transform(heart_disease_df['prevalentStroke'])

# Convert 'Heart_stroke' column to integers
heart_disease_df['Heart_ stroke'] = label_encoder.fit_transform(heart_disease_df['Heart_ stroke'])

# Display the updated dataframe
print(heart_disease_df.head())

   Gender  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0       1   39          1              0         0.0     0.0                0
1       0   46          2              0         0.0     0.0                0
2       1   48          3              1        20.0     0.0                0
3       0   61          0              1        30.0     0.0                0
4       0   46          0              1        23.0     0.0                0

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0

   Heart_ stroke
0              0
1              0
2              0
3              1
4              0

## Helpful resources 
Don't forget to cite websites which helped you solve a problem in a unique way.  You can do this in markdown near the code or with a simple one-line comment inside the code cell, or you can list them below. 

You do not need to cite the official python documentation.